config/routes.rb
Rails.application.routes.draw do
  
  
  devise_for :users
  get "pages/index"

  get "pages/about"

  get "pages/help"

root "pages#about"

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
   def resource_name
    :user
  end
  
  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>

<html>
	<head>
		<title>RailsProject</title>
		<%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
		<%= javascript_include_tag "application", "data-turbolinks-track" => true %>
		<%= csrf_meta_tags %>
	</head>
	<body>
		<%= render "pages/nav" %>

		<%= render "pages/messages" %>

		<%= yield %>

		<%= render "pages/footer" %>
	</body>
</html>

app/views/pages/_footer.html.erb
<p class="footer navbar-fixed-bottom">
	easyMeetings © Naglis Piatkovskis, 2014
</p>

app/views/pages/_messages.html.erb
<% if (alert != nil) %>
	<div class="alert alert-danger text-center col-sm-4 col-sm-offset-4">
		<!-- <div class="container"> -->
			<%= alert %>
		</div>
	<!-- </div> -->
<% end %>

<% if (notice != nil) %>
	<div class="alert alert-info text-center col-sm-4 col-sm-offset-4">
		<!-- <div class="container"> -->
			<%= notice %>
		</div>
	<!-- </div> -->
<% end %>

app/views/pages/_nav.html.erb
<div class="navbar navbar-inverse navbar-static-top" role="navigation">
	<div class="container">
		<div class="navbar-header">
			<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
				<span class="sr-only">Toggle navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<a class="navbar-brand" href="/">easyMeetings</a>
		</div>
		<div class="collapse navbar-collapse">
			<ul class="nav navbar-nav">
				<li>
					<%= link_to "About", "/pages/about"  %>
				</li>
			</ul>
			<ul class="nav navbar-nav navbar-right">

				<% if !user_signed_in? %>
				<li>
					<a href="#signin" role="button" id="signinButton">Sign In</a>
				</li>
				<li>
					<a href="#signup"  role="button" id="signupButton">Register</a>
				</li>
				<% else %>
				<li>
					<%= link_to "Log out (" + current_user.email + ")", destroy_user_session_path, :method => :delete %>
					
				</li>
				<% end %>
			</ul>
		</div>
		<!--/nav-collapse -->
	</div>
</div>


<%= render 'pages/singinsingup' %>

app/views/pages/_singinsingup.html.erb
<div class="modal fade bs-modal-sm" id="myModal" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel" aria-hidden="true">
	<div class="modal-dialog modal-sm">
		<div class="modal-content">
			<br>
			<div class="bs-example bs-example-tabs">
				<ul id="myTab" class="nav nav-tabs">
					<li class="active">
						<a href="#signin" data-toggle="tab">Sign In</a>
					</li>
					<li class="">
						<a href="#signup" data-toggle="tab">Register</a>
					</li>
				</ul>
			</div>
			<div class="modal-body">
				<div id="myTabContent" class="tab-content">
					<div class="tab-pane fade active in" id="signin">
						<%= form_for(resource, :as => resource_name, :url => session_path(resource_name), :class => "form-horizontal") do |f| %>
						<fieldset>
							<!-- Sign In Form -->
							<!-- Email input-->
							<div class="control-group">
								<label class="control-label" for="Email">Email:</label>
								<div class="controls">
									<%= f.email_field :email, :autofocus => true, :placeholder => "Email", :class => "form-control input-md" %>
								</div>
							</div>

							<!-- Password input-->
							<div class="control-group">
								<label class="control-label" for="passwordinput">Password:</label>
								<div class="controls">
									<%= f.password_field :password, :placeholder => "Password", :class => "form-control input-md" %>
								</div>
							</div>

							<!-- Multiple Checkboxes (inline) -->
							<% if devise_mapping.rememberable? -%>
							<div class="checkbox">
									<%= f.check_box :remember_me %> <%= f.label :remember_me %>
							</div>
							<% end -%>

							<!-- Button -->
							<div class="control-group">
								<label class="control-label" for="signin"></label>
								<div class="controls">
									<%= f.submit "Sign in", :class => "btn btn-success" %>
								</div>
							</div>
							<br>
							<div class="control-group pull-right">
								<%= link_to "Forgot your password?", new_password_path(resource_name) %>
							</div>
						</fieldset>
						<% end %>
					</div>
					
					<div class="tab-pane fade" id="signup">
						<%= form_for(resource, :as => resource_name, :url => registration_path(resource_name), :class => "form-horizontal") do |f| %>
						<%= devise_error_messages! %>
							<fieldset>
								<!-- Sign Up Form -->
								<!-- Text input-->
								<div class="control-group">
									<label class="control-label" for="Email">Email:</label>
									<div class="controls">
										<%= f.email_field :email, :autofocus => true, :placeholder => "Email", :class => "form-control input-md" %>
									</div>
								</div>

								<!-- Password input-->
								<div class="control-group">
									<label class="control-label" for="password">Password:</label>
									<div class="controls">
										<%= f.password_field :password, :placeholder => "Password", :class => "form-control input-md" %>
										<em>1-8 Characters</em>
									</div>
								</div>

								<!-- Text input-->
								<div class="control-group">
									<label class="control-label" for="reenterpassword">Re-Enter Password:</label>
									<div class="controls">
										<%= f.password_field :password_confirmation, :placeholder => "Re-Enter password", :class => "form-control input-md" %>
									</div>
								</div>

								<!-- Button -->
								<div class="control-group">
									<label class="control-label" for="confirmsignup"></label>
									<div class="controls">
										<%= f.submit "Sign up", :class =>  "btn btn-success"%>
									</div>
								</div>
							</fieldset>
						<% end %>
					</div>
				</div>
			</div>
			<div class="modal-footer">
				<center>
					<button type="button" class="btn btn-default" data-dismiss="modal">
						Close
					</button>
				</center>
			</div>
		</div>
	</div>
</div>

app/views/pages/about.html.erb
<div class="container">
<h1>About <small>easyMeetings	</small></h1>

<p>Small web application, which allow to schedule some meeting within different timezones and raise and free video call with everyone.
</p>
</div>